#pragma once

#include "event.h"
#include <memory>
#include <queue>

class ExecutionHandler {
	// The ExecutionHandler handles the interaction
	// between a set of order objects generated by a Portfolio and
	// the set of Fill objects.
public:
	// Takes an OrderEvent and executes it, producing
	// a FillEvent that gets placed onto the event queue.
	//
	// 'event' - OrderEvent object
	virtual void execute_order(const Event& event) = 0;
	virtual ~ExecutionHandler() = default;
};

class SimulatedExecutionHandler : public ExecutionHandler {
	std::queue<std::unique_ptr<Event>>& events;
public:
	explicit SimulatedExecutionHandler(std::queue<std::unique_ptr<Event>>& events_);

	void execute_order(const Event& event) override;
};
