#include "event.h"
#include <queue>
#include <memory>
#include <chrono>

// will represent a simulated order handling mechanism and
// ultimately tie into a brokerage or other means of market connectivity


class ExecutionHandler {
//     The ExecutionHandler abstract class handles the interaction
// between a set of order objects generated by a Portfolio and
// the ultimate set of Fill objects that actually occur in the
// market.
//
public:
    // Takes an Order event and executes it, producing
    // a Fill event that gets placed onto the Events queue.
    //
    //     Parameters:
    //     event - Contains an Event object with order information.
    virtual void execute_order(const OrderEvent& event) = 0;
    virtual ~ExecutionHandler() = default;
};


class SimulatedExecutionHandler : public ExecutionHandler {
    std::queue<std::unique_ptr<Event>>& events;
public:
    explicit SimulatedExecutionHandler(std::queue<std::unique_ptr<Event>>& events_): events(events_) {}

    void execute_order(const Event& event) override {
        // Just check the type
        //TODO implement modern c++
        if (event.type() != EventType::ORDER)
            return;

        auto& order = dynamic_cast<OrderEvent&>(event);

        // Creare FillEvent
        auto fill = std::make_unique<FillEvent>(
            std::chrono::system_clock::now(),  // время исполнения
            order.get_symbol(),
            "SIM_EXCHANGE",                    // place holder
            order.get_quantity(),
            order.get_direction(),
            0.0                             // fill_cost (можно 0 или рассчитанное значение)
        );
        events.push(std::move(fill));
    }
};