#pragma once

#include "event.h"
#include <memory>
#include <queue>

// will represent a simulated order handling mechanism and
// ultimately tie into a brokerage or other means of market connectivity

class ExecutionHandler {
	//     The ExecutionHandler abstract class handles the interaction
	// between a set of order objects generated by a Portfolio and
	// the ultimate set of Fill objects that actually occur in the
	// market.
	//
public:
	// Takes an Order event and executes it, producing
	// a Fill event that gets placed onto the Events queue.
	//
	//     Parameters:
	//     event - Contains an Event object with order information.
	virtual void execute_order(const Event& event) = 0;
	virtual ~ExecutionHandler() = default;
};

class SimulatedExecutionHandler : public ExecutionHandler {
	std::queue<std::unique_ptr<Event>>& events;
public:
	explicit SimulatedExecutionHandler(std::queue<std::unique_ptr<Event>>& events_);

	void execute_order(const Event& event) override;
};
