#pragma once

#include "event.h"
#include <map>
#include <string>

class Strategy {
	// A Strategy object encapsulates all calculations on
	// market data that generate ADVISORY signals to a Portfolio object.
public:
	virtual ~Strategy() = default;

	// This the method that handles the generation of SignalEvent objects
	// based on the inputs of Bar objects generated by a DataHandler object.
	virtual void calculate_signals(const Event& event) = 0;

	virtual void plot() = 0;
	virtual std::map<std::string, double> get_indicators() const {
		return {}; // default: no indicators
	}
};
